### ISSUE TITLE
can't work on 2.1.33

### ISSUE THREAD

**Issue by freemedom** [Arthur-Milchior/anki-keep-card-in-reviewer#1]
can work on 2.1.26
______
but can't work on 2.1.33
——————————————
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-20 09:27:18

Caught exception:
Traceback (most recent call last):
File "aqt\main.py", line 1065, in onEditCurrent
File "aqt\__init__.py", line 105, in open
File "aqt\editcurrent.py", line 31, in __init__
TypeError: requireReset() got an unexpected keyword argument 'reason'
——————————————————
https://ankiweb.net/shared/info/1894745652

**Comment by freemedom** [comment]
i find some changes,but i can't understand them and correct them
https://github.com/ankitects/anki/commit/7f503895d7699dee984e887341265a005b7ba629
https://github.com/ankitects/anki/commit/db0a18106fe739e247f6a22afe5f2fd1f6b4008f
https://github.com/ankitects/anki/commit/dd515e65e76e69a0adbd82589c2edbf80eea54e4

**Comment by Arthur-Milchior** [comment]
Thanks for the bug report. I guess I'll need to take a look at it sometime. I don't have any idea what change occured, anki change a lot and I have not been able to keep up to date
